"""Remove type attribute from transaction table

Revision ID: 17922cf1066a
Revises: 1cbc17458ee5
Create Date: 2025-06-19 19:01:34.040900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17922cf1066a'
down_revision = '1cbc17458ee5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=10), nullable=False))

    # ### end Alembic commands ###
