"""Add type, user_id, is_default to Category

Revision ID: 82cce2e5f51d
Revises: 658bcdf89114
Create Date: 2025-08-06 13:36:32.428099

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '82cce2e5f51d'
down_revision = '658bcdf89114'
branch_labels = None
depends_on = None


def upgrade():
    category_type = postgresql.ENUM('income', 'expense', name = 'category_type')
    category_type.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
        batch_op.alter_column('type',
            existing_type=sa.VARCHAR(length=10),
            type_=sa.Enum('income', 'expense', name='category_type'),
            existing_nullable=False,
            postgresql_using="type::category_type")
        batch_op.drop_constraint(batch_op.f('categories_name_key'), type_='unique')
        batch_op.create_unique_constraint('uq_category_name_user', ['name', 'user_id'])
        batch_op.drop_column('last_updated')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_updated', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
        batch_op.drop_constraint('uq_category_name_user', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('categories_name_key'), ['name'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('type',
               existing_type=sa.Enum('income', 'expense', name='category_type'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
